Repository vshn/odootools, pull requests merged in 2022-03, with the labels that each got.

#71 Fix date range calculations of yearly report
  pkg/web/overtimereport/overtimereport_controller.go
  pkg/web/reportconfig/config_request.go
Labels: bug

#67 Write payslip
  Makefile
  pkg/odoo/model/payslip.go
  pkg/web/controller/controller.go
  pkg/web/controller/view.go
  pkg/web/controller/view_test.go
  pkg/web/employeereport/employeereport_controller.go
  pkg/web/employeereport/employeereport_view.go
  pkg/web/employeereport/employeereport_view_test.go
  pkg/web/employeereport/update_payslip_controller.go
  pkg/web/employeereport/update_request.go
  pkg/web/overtimereport/overtimereport_controller.go
  pkg/web/report_handler.go
  pkg/web/reportconfig/config_controller.go
  pkg/web/reportconfig/config_request.go
  pkg/web/routes.go
  pkg/web/server.go
  templates/bootstrap.min.js
  templates/bootstrap.min.js.map
  templates/embed.go
  templates/employeereport.html
  templates/help.html
  templates/layout.html
Labels: enhancement

#83 Add a weekly report to the config view
  pkg/odoo/date.go
  pkg/odoo/model/attendance.go
  pkg/odoo/model/attendance_test.go
  pkg/odoo/model/contract.go
  pkg/odoo/model/odoo_test.go
  pkg/timesheet/report.go
  pkg/timesheet/report_test.go
  pkg/timesheet/yearly_report.go
  pkg/timesheet/yearly_report_test.go
  pkg/web/controller/view.go
  pkg/web/employeereport/employeereport_controller.go
  pkg/web/employeereport/employeereport_view.go
  pkg/web/overtimereport/monthlyreport_view.go
  pkg/web/overtimereport/overtimereport_controller.go
  pkg/web/overtimereport/yearlyreport_view.go
  pkg/web/report_handler.go
  pkg/web/reportconfig/config_controller.go
  pkg/web/reportconfig/config_controller_test.go
  pkg/web/reportconfig/config_request.go
  pkg/web/reportconfig/config_view.go
  templates/createreport.html
Labels: enhancement

#84 Display a warning if weekly report can't be generated
  pkg/web/reportconfig/config_controller.go
  pkg/web/reportconfig/config_view.go
  templates/createreport.html
Labels: change
