Repository vshn/odootools, pull requests merged in 2022-02, with the labels that each got.

#56 Refactor odoo package
  Makefile
  cmd/web.go
  go.mod
  go.sum
  main.go
  pkg/odoo/attendance.go
  pkg/odoo/client.go
  pkg/odoo/client_test.go
  pkg/odoo/date.go
  pkg/odoo/date_test.go
  pkg/odoo/debug.go
  pkg/odoo/employee.go
  pkg/odoo/jsonrpc.go
  pkg/odoo/model.go
  pkg/odoo/model/actionreason.go
  pkg/odoo/model/attendance.go
  pkg/odoo/model/attendance_test.go
  pkg/odoo/model/contract.go
  pkg/odoo/model/contract_test.go
  pkg/odoo/model/employee.go
  pkg/odoo/model/leave.go
  pkg/odoo/model/leave_test.go
  pkg/odoo/model/odoo.go
  pkg/odoo/model/odoo_test.go
  pkg/odoo/model/payslip.go
  pkg/odoo/model/payslip_test.go
  pkg/odoo/model/workingschedule.go
  pkg/odoo/model/workingschedule_test.go
  pkg/odoo/session.go
  pkg/odoo/session_test.go
  pkg/timesheet/report.go
  pkg/timesheet/report_test.go
  pkg/timesheet/yearly_report.go
  pkg/timesheet/yearly_report_test.go
  pkg/web/controller/context.go
  pkg/web/overtimereport/monthlyreport_view.go
  pkg/web/overtimereport/overtimereport_controller.go
  pkg/web/server.go
  pkg/web/session_handlers.go
  test/dashboard_test.go
  test/integration_test.go
  test/static_test.go
  tools.go
  web_command.go
Labels: change

#57 Add help page
  pkg/web/routes.go
  pkg/web/server.go
  renovate.json
  templates/help.html
  templates/nav.html
Labels: documentation

#59 Development: Support running/building with Podman
  Makefile
  Makefile.vars.mk
Labels: change

#60 Check user permissions and disable UI actions if missing permissions
  pkg/odoo/model/actionreason_test.go
  pkg/odoo/model/groupcategory.go
  pkg/odoo/model/groupcategory_test.go
  pkg/odoo/model/groups.go
  pkg/web/controller/context.go
  pkg/web/overtimereport/config_controller.go
  pkg/web/overtimereport/config_view.go
  pkg/web/overtimereport/overtimereport_controller.go
  pkg/web/server.go
  templates/createreport.html
Labels: enhancement

#58 Ensure `make run` can actually run odootools
  Makefile
Labels: change

#61 Tell units when it's not hours in yearly report
  templates/overtimereport-yearly.html
Labels: change

#64 Abort reporting with error when contracts cannot be accessed
  pkg/timesheet/report.go
  pkg/timesheet/report_test.go
  pkg/timesheet/yearly_report.go
  pkg/web/overtimereport/overtimereport_controller.go
Labels: bug

#63 Save static information in cookie
  go.mod
  go.sum
  pkg/web/controller/context.go
  pkg/web/cookie.go
  pkg/web/overtimereport/config_controller.go
  pkg/web/overtimereport/overtimereport_controller.go
  pkg/web/server.go
  pkg/web/server_test.go
  pkg/web/session_handlers.go
  pkg/web/session_handlers_test.go
  templates/help.html
  test/session_test.go
Labels: enhancement

#66 List of all Employees and overtime summary
  go.mod
  go.sum
  pkg/odoo/model/employee.go
  pkg/timesheet/report.go
  pkg/timesheet/report_test.go
  pkg/web/controller/controller.go
  pkg/web/controller/view.go
  pkg/web/controller/view_test.go
  pkg/web/employeereport/employeereport_controller.go
  pkg/web/employeereport/employeereport_view.go
  pkg/web/overtimereport/config_controller.go
  pkg/web/overtimereport/monthlyreport_view.go
  pkg/web/overtimereport/overtimereport_controller.go
  pkg/web/overtimereport/overtimereport_request.go
  pkg/web/overtimereport/yearlyreport_view.go
  pkg/web/report_handler.go
  pkg/web/reportconfig/config_controller.go
  pkg/web/reportconfig/config_request.go
  pkg/web/reportconfig/config_view.go
  pkg/web/routes.go
  pkg/web/server.go
  templates/createreport.html
  templates/employeereport.html
  templates/error.html
  templates/help.html
  templates/login.html
  templates/overtimereport-monthly.html
  templates/overtimereport-yearly.html
Labels: enhancement
