Repository vshn/odootools, pull requests merged in 2023-01, with the labels that each got.

#163 Remove radio check for HR manager
  pkg/web/reportconfig/config_request.go
  templates/createreport.html
Labels: change

#164 Aligned hours column to the right and change font to monospace
  templates/createreport.html
  templates/overtimereport-monthly.html
  templates/overtimereport-yearly.html
Labels: enhancement

#165 Change Overtime & Undertime color
  pkg/web/controller/view.go
  pkg/web/controller/view_test.go
  pkg/web/overtimereport/monthlyreport_view.go
  pkg/web/overtimereport/yearlyreport_view.go
  templates/createreport.html
  templates/help.html
  templates/overtimereport-monthly.html
  templates/overtimereport-yearly.html
Labels: enhancement

#166 Change fontsize to bold
  templates/createreport.html
  templates/overtimereport-monthly.html
  templates/overtimereport-yearly.html
Labels: change

#167 Limit the max width for very wide screens
  templates/layout.html
Labels: change

#168 Space out items on navbar
  templates/nav.html
Labels: change

#169 Add missing colorization to employee report
  pkg/web/controller/view.go
  pkg/web/employeereport/employeereport_view.go
  pkg/web/overtimereport/monthlyreport_view.go
  templates/createreport.html
  templates/employeereport.html
  templates/overtimereport-monthly.html
  templates/overtimereport-yearly.html
Labels: bug
